/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UIPackage;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class AskQuestion extends javax.swing.JFrame {

    /**
     * Creates new form AskQuestion
     */
    public AskQuestion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtGetUsername = new javax.swing.JTextField();
        btnCheckUsername = new javax.swing.JButton();
        lblPreviewQuestion = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtGetAnswer = new javax.swing.JTextField();
        btnCheckAnswer = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Enter Your Username:-");

        txtGetUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGetUsernameActionPerformed(evt);
            }
        });

        btnCheckUsername.setText("Submit");
        btnCheckUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckUsernameActionPerformed(evt);
            }
        });

        jLabel3.setText("Enter Your Answer:-");

        btnCheckAnswer.setText("Submit");
        btnCheckAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckAnswerActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(lblPreviewQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addGap(74, 74, 74)
                                .addComponent(btnCheckAnswer))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(71, 71, 71)
                                    .addComponent(txtGetAnswer))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnCheckUsername)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(129, 129, 129)
                                        .addComponent(txtGetUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtGetUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btnCheckUsername)
                .addGap(46, 46, 46)
                .addComponent(lblPreviewQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtGetAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCheckAnswer)
                    .addComponent(btnBack))
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGetUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGetUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGetUsernameActionPerformed

    private void btnCheckUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckUsernameActionPerformed
        if (txtGetUsername.getText().isEmpty()) {
             JOptionPane.showMessageDialog(rootPane, "Please Enter Username", "Forgot Password", JOptionPane.ERROR_MESSAGE);
        }
        else{
        
        String Username=txtGetUsername.getText();
             try {
                    String url = "jdbc:derby://localhost:1527/TheTechCompany";
                    Connection con = DriverManager.getConnection(url, "abc", "123");
                    Statement stmt = con.createStatement();
                      String query = "SELECT QUESTION FROM Login WHERE USERNAME = '" + Username + "'";
            ResultSet rs = stmt.executeQuery(query);
            if (rs.next()) {
                // If a row is returned, retrieve the question from the result set
                String question = rs.getString("QUESTION");
                // Do something with the retrieved question (e.g., display it)
                 lblPreviewQuestion.setText("Security Question: " + question);
            } else {
                // If no row is returned, the username is not found
                JOptionPane.showMessageDialog(rootPane, "Username not found", "Forgot Password", JOptionPane.ERROR_MESSAGE);
            }
             rs.close();
            stmt.close();
            con.close();
        
        }   catch (SQLException ex) {
                Logger.getLogger(AskQuestion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnCheckUsernameActionPerformed

    private void btnCheckAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckAnswerActionPerformed
 if (txtGetAnswer.getText().isEmpty()) {
             JOptionPane.showMessageDialog(rootPane, "Please Enter Your Answer ", "Forgot Password", JOptionPane.ERROR_MESSAGE);
        }  
 else{
     
       String Username=txtGetUsername.getText();
       String Answer=txtGetAnswer.getText();
  try {
                    String url = "jdbc:derby://localhost:1527/TheTechCompany";
                    Connection con = DriverManager.getConnection(url, "abc", "123");
                    Statement stmt = con.createStatement();
                      String query = "SELECT ANSWER FROM Login WHERE USERNAME = '" + Username + "'";
            ResultSet rs = stmt.executeQuery(query);
              if (rs.next()) {
                // If a row is returned, retrieve the answer from the result set
                String storedAnswer = rs.getString("ANSWER");
                
                // Compare the stored answer with the user's answer
                if (Answer.equals(storedAnswer)) {
                    JOptionPane.showMessageDialog(rootPane, "Answer is correct. You can reset your password.", "Forgot Password", JOptionPane.INFORMATION_MESSAGE);
                   new ResetPassword().setVisible(true);
                   this.dispose();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Answer is incorrect. Please try again.", "Forgot Password", JOptionPane.ERROR_MESSAGE);
                }
               } else {
                // If no row is returned, the username is not found
                JOptionPane.showMessageDialog(rootPane, "Username not found", "Forgot Password", JOptionPane.ERROR_MESSAGE);
            }
                rs.close();
            stmt.close();
            con.close();
 
 }   catch (SQLException ex) {
         Logger.getLogger(AskQuestion.class.getName()).log(Level.SEVERE, null, ex);
     }
 }
    }//GEN-LAST:event_btnCheckAnswerActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
         new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AskQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AskQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AskQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AskQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AskQuestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCheckAnswer;
    private javax.swing.JButton btnCheckUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPreviewQuestion;
    private javax.swing.JTextField txtGetAnswer;
    private javax.swing.JTextField txtGetUsername;
    // End of variables declaration//GEN-END:variables
}
