/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UIPackage;

import javax.swing.JOptionPane;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.jar.Attributes.Name;

/**
 *
 * @author User
 */
public class Paysheet extends javax.swing.JFrame {

    String EPFNumber;
    String Desig;
    String NIC;
    Double Sallary;
    Double EPFDeduction;
    Double NetAmount;
    Double conve = 3000.00;
    Double HRA = 2000.00;
    Double Fund = 300.00;
    String Name;

    /**
     * Creates new form Paysheet
     */
    public Paysheet() {
        initComponents();
        txtName.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtEPFNumber = new javax.swing.JTextField();
        txtNIC = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        erea = new javax.swing.JTextArea();
        btnReset = new javax.swing.JButton();
        btnPreview = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Paysheet");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Employee Name :-");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 120, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Employee EPF Number :-");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 160, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NIC Number :-");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 103, -1));

        txtName.setBackground(new java.awt.Color(102, 102, 102));
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 72, 110, -1));

        txtEPFNumber.setBackground(new java.awt.Color(102, 102, 102));
        txtEPFNumber.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtEPFNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 110, -1));

        txtNIC.setBackground(new java.awt.Color(102, 102, 102));
        txtNIC.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(txtNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 260, 110, -1));

        erea.setColumns(20);
        erea.setRows(5);
        jScrollPane1.setViewportView(erea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 18, 250, 412));

        btnReset.setText("Reset");
        btnReset.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 57, 20));

        btnPreview.setText("Preview ");
        btnPreview.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviewActionPerformed(evt);
            }
        });
        jPanel1.add(btnPreview, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 60, 20));

        btnPrint.setText("Print");
        btnPrint.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 60, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel4.setText("Fill the details:-");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 18, 111, -1));

        jButton1.setText("Back");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 62, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\income-illustration-with-businessman_169241-92.jpg")); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 450));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviewActionPerformed
        if (txtName.getText().isEmpty() || txtEPFNumber.getText().isEmpty() || txtNIC.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Fill the all details", "Paysheet", JOptionPane.WARNING_MESSAGE);

        } else {
            try {
                Name = txtName.getText().toString();
                String Number = txtEPFNumber.getText().toString();

                NIC = txtNIC.getText().toString();
                String url = "jdbc:derby://localhost:1527/TheTechCompany";
                Connection con = DriverManager.getConnection(url, "abc", "123");
                Statement stmt = con.createStatement();

                String qry = "SELECT * FROM Employee WHERE epfNumber = ?";
                PreparedStatement preparedStatement = con.prepareStatement(qry);
                preparedStatement.setString(1, Number);
                ResultSet rs = preparedStatement.executeQuery();
                while (rs.next()) {

                    EPFNumber = rs.getString("EPFNUMBER");
                    Desig = rs.getString("DESIGNATION");
                    Sallary = rs.getDouble("SALLARY");

                    EPFDeduction = Sallary * 8 / 100;
                    NetAmount = (Sallary + conve + HRA) - (EPFDeduction + Fund);

                }

            } catch (SQLException e) {
                System.out.println(e);
            }

        }

        erea.setText("-------------------------------------------------\n");
        erea.setText(erea.getText() + "*               The Tech Company           *\n");
        erea.setText(erea.getText() + "-------------------------------------------------\n");
        Date obj = new Date();

        String date = obj.toString();

        erea.setText(erea.getText() + "No 27 East Drive Lane,Colombo 06 \n");
        erea.setText(erea.getText() + "Employee Name:-" + Name + "\n");
        erea.setText(erea.getText() + "Employee EPF Number:-" + EPFNumber + "\n");
        erea.setText(erea.getText() + "Designation :-" + Desig + "\n");
        erea.setText(erea.getText() + "Employee NIC:-" + NIC + "\n\n");
        erea.setText(erea.getText() + "Earnings                                      Rs\n");
        erea.setText(erea.getText() + "-------------------------------------------------\n");
        erea.setText(erea.getText() + "Basic                                      " + Sallary + "\n");
        erea.setText(erea.getText() + "Conveyance                             " + conve + "\n");
        erea.setText(erea.getText() + "HRA                                         " + HRA + "\n\n");
        erea.setText(erea.getText() + "Deductions                                      Rs\n");
        erea.setText(erea.getText() + "--------------------------------------------------\n");
        erea.setText(erea.getText() + "Provide Fund                                " + Fund + "\n");
        erea.setText(erea.getText() + "EPF Contribution                        " + EPFDeduction + "\n");
        erea.setText(erea.getText() + "-------------------------------------------------\n");
        erea.setText(erea.getText() + "Total Amount                            " + NetAmount + "\n");
    }//GEN-LAST:event_btnPreviewActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        erea.setText("");
        txtEPFNumber.setText("");
        txtNIC.setText("");
        txtName.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed

        try {

            erea.print();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new AssistentMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paysheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paysheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paysheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paysheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paysheet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPreview;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnReset;
    private javax.swing.JTextArea erea;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtEPFNumber;
    private javax.swing.JTextField txtNIC;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
